// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nwwzhuhixnhbodgwyagk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53d3podWhpeG5oYm9kZ3d5YWdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4ODgzOTAsImV4cCI6MjA1ODQ2NDM5MH0.lxqxZOQV5ete2VRkHxMCbHCzykxhQa0sxrTh4qlrHB8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);